/*
 * Hospital Resource Utilization Analytics - Java companion reporter
 * BE Computer Engineering | Big Data Analytics mini-project
 *
 * Reads the CSV exported by the Python pipeline and prints a text report.
 * Dependency-light: only the Java standard library is used.
 *
 * Compile & run:
 *   javac ReportSummary.java
 *   java ReportSummary ../data/analysis_results.csv
 */

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public class ReportSummary {

    public static void main(String[] args) throws Exception {
        String path = args.length > 0 ? args[0] : "../data/analysis_results.csv";

        List<String[]> rows = new ArrayList<>();
        String[] header;
        try (BufferedReader br = new BufferedReader(new FileReader(path))) {
            header = br.readLine().split(",");
            String line;
            while ((line = br.readLine()) != null) {
                if (!line.trim().isEmpty()) rows.add(line.split(",", -1));
            }
        }

        Map<String, Integer> col = new LinkedHashMap<>();
        for (int i = 0; i < header.length; i++) col.put(header[i].trim(), i);

        int total = rows.size();
        double occSum = 0, predSum = 0, absErrSum = 0;
        int highCount = 0;
        Map<String, double[]> byDept = new LinkedHashMap<>(); // dept -> {occSum, count, predSum}

        for (String[] r : rows) {
            double occRate = Double.parseDouble(r[col.get("occupancy_rate")]);
            double pred = Double.parseDouble(r[col.get("predicted_occupied_beds")]);
            double actual = Double.parseDouble(r[col.get("occupied_beds")]);
            String cluster = r[col.get("utilization_cluster")].trim();
            String dept = r[col.get("department")].trim();

            occSum += occRate;
            predSum += pred;
            absErrSum += Math.abs(actual - pred);
            if (cluster.startsWith("High")) highCount++;

            double[] agg = byDept.computeIfAbsent(dept, k -> new double[3]);
            agg[0] += occRate;
            agg[1] += 1;
            agg[2] += pred;
        }

        System.out.println("========================================================");
        System.out.println(" HOSPITAL RESOURCE UTILIZATION ANALYTICS - SUMMARY REPORT");
        System.out.println(" Source: " + path + "   (synthetic academic dataset)");
        System.out.println("========================================================");
        System.out.printf(" Total records analysed     : %d%n", total);
        System.out.printf(" Departments                : %d%n", byDept.size());
        System.out.printf(" Average occupancy rate     : %.2f %%%n", occSum / total);
        System.out.printf(" High-utilization records   : %d (%.1f %%)%n",
                highCount, 100.0 * highCount / total);
        System.out.printf(" Avg predicted occupied beds: %.2f%n", predSum / total);
        System.out.printf(" Mean absolute error (beds) : %.2f%n", absErrSum / total);
        System.out.println("--------------------------------------------------------");
        System.out.printf(" %-18s %12s %14s%n", "DEPARTMENT", "AVG OCC %", "AVG PRED BEDS");
        for (Map.Entry<String, double[]> e : byDept.entrySet()) {
            double[] a = e.getValue();
            System.out.printf(" %-18s %12.2f %14.2f%n", e.getKey(), a[0] / a[1], a[2] / a[1]);
        }
        System.out.println("========================================================");
        System.out.println(" Report generated by the Java companion component.");
    }
}
