/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BdaAnalysisRouteImport } from './routes/bda-analysis'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DataExplorerRouteImport } from './routes/data-explorer'
import { Route as PowerBiGuideRouteImport } from './routes/power-bi-guide'
import { Route as RunProjectRouteImport } from './routes/run-project'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BdaAnalysisRoute = BdaAnalysisRouteImport.update({
  id: '/bda-analysis',
  path: '/bda-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DataExplorerRoute = DataExplorerRouteImport.update({
  id: '/data-explorer',
  path: '/data-explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const PowerBiGuideRoute = PowerBiGuideRouteImport.update({
  id: '/power-bi-guide',
  path: '/power-bi-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const RunProjectRoute = RunProjectRouteImport.update({
  id: '/run-project',
  path: '/run-project',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bda-analysis': typeof BdaAnalysisRoute
  '/dashboard': typeof DashboardRoute
  '/data-explorer': typeof DataExplorerRoute
  '/power-bi-guide': typeof PowerBiGuideRoute
  '/run-project': typeof RunProjectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bda-analysis': typeof BdaAnalysisRoute
  '/dashboard': typeof DashboardRoute
  '/data-explorer': typeof DataExplorerRoute
  '/power-bi-guide': typeof PowerBiGuideRoute
  '/run-project': typeof RunProjectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bda-analysis': typeof BdaAnalysisRoute
  '/dashboard': typeof DashboardRoute
  '/data-explorer': typeof DataExplorerRoute
  '/power-bi-guide': typeof PowerBiGuideRoute
  '/run-project': typeof RunProjectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bda-analysis'
    | '/dashboard'
    | '/data-explorer'
    | '/power-bi-guide'
    | '/run-project'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bda-analysis'
    | '/dashboard'
    | '/data-explorer'
    | '/power-bi-guide'
    | '/run-project'
  id:
    | '__root__'
    | '/'
    | '/bda-analysis'
    | '/dashboard'
    | '/data-explorer'
    | '/power-bi-guide'
    | '/run-project'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BdaAnalysisRoute: typeof BdaAnalysisRoute
  DashboardRoute: typeof DashboardRoute
  DataExplorerRoute: typeof DataExplorerRoute
  PowerBiGuideRoute: typeof PowerBiGuideRoute
  RunProjectRoute: typeof RunProjectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bda-analysis': {
      id: '/bda-analysis'
      path: '/bda-analysis'
      fullPath: '/bda-analysis'
      preLoaderRoute: typeof BdaAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-explorer': {
      id: '/data-explorer'
      path: '/data-explorer'
      fullPath: '/data-explorer'
      preLoaderRoute: typeof DataExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/power-bi-guide': {
      id: '/power-bi-guide'
      path: '/power-bi-guide'
      fullPath: '/power-bi-guide'
      preLoaderRoute: typeof PowerBiGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run-project': {
      id: '/run-project'
      path: '/run-project'
      fullPath: '/run-project'
      preLoaderRoute: typeof RunProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BdaAnalysisRoute: BdaAnalysisRoute,
  DashboardRoute: DashboardRoute,
  DataExplorerRoute: DataExplorerRoute,
  PowerBiGuideRoute: PowerBiGuideRoute,
  RunProjectRoute: RunProjectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
