/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BdaAnalysisRouteImport } from './routes/bda-analysis'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DataExplorerRouteImport } from './routes/data-explorer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BdaAnalysisRoute = BdaAnalysisRouteImport.update({
  id: '/bda-analysis',
  path: '/bda-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DataExplorerRoute = DataExplorerRouteImport.update({
  id: '/data-explorer',
  path: '/data-explorer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bda-analysis': typeof BdaAnalysisRoute
  '/dashboard': typeof DashboardRoute
  '/data-explorer': typeof DataExplorerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bda-analysis': typeof BdaAnalysisRoute
  '/dashboard': typeof DashboardRoute
  '/data-explorer': typeof DataExplorerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bda-analysis': typeof BdaAnalysisRoute
  '/dashboard': typeof DashboardRoute
  '/data-explorer': typeof DataExplorerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bda-analysis' | '/dashboard' | '/data-explorer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bda-analysis' | '/dashboard' | '/data-explorer'
  id: '__root__' | '/' | '/bda-analysis' | '/dashboard' | '/data-explorer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BdaAnalysisRoute: typeof BdaAnalysisRoute
  DashboardRoute: typeof DashboardRoute
  DataExplorerRoute: typeof DataExplorerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bda-analysis': {
      id: '/bda-analysis'
      path: '/bda-analysis'
      fullPath: '/bda-analysis'
      preLoaderRoute: typeof BdaAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-explorer': {
      id: '/data-explorer'
      path: '/data-explorer'
      fullPath: '/data-explorer'
      preLoaderRoute: typeof DataExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BdaAnalysisRoute: BdaAnalysisRoute,
  DashboardRoute: DashboardRoute,
  DataExplorerRoute: DataExplorerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
